name: Test and Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test FastAPI App
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements.txt
        pip install pytest httpx

    - name: Run tests
      run: |
        cd app
        python -m pytest tests/ -v || echo "No tests found, skipping..."

    - name: Test Docker build
      run: |
        cd app
        docker build -t fastapi-app:test .
        
    - name: Test container runs
      run: |
        cd app
        docker run -d --name test-container -p 8000:8000 fastapi-app:test
        sleep 5
        curl -f http://localhost:8000/ || exit 1
        curl -f http://localhost:8000/health || exit 1
        docker stop test-container
        docker rm test-container